name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: tox

      - name: Create default secrets.toml
        run: |
          mkdir -p ~/.streamlit
          echo "[general]" > ~/.streamlit/secrets.toml
          echo "imap_server = 'default_imap_server'" >> ~/.streamlit/secrets.toml
          echo "email_account = 'default_email_account'" >> ~/.streamlit/secrets.toml
          echo "email_password = 'default_password'" >> ~/.streamlit/secrets.toml
          echo "openai_api_key = 'default_openai_api_key'" >> ~/.streamlit/secrets.toml


      - name: Streamlit
        uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: src/your_mail_buddy/app.py
          ruff: true
